### ISSUE TITLE
Looks really good!

### ISSUE THREAD

**Issue by daniel-dressler** [ufna/VaOceanMobile#1]
Hey I just wanted to say thank you for this. I have been looking all over for an ocean shader. I am just a programmer and the artist asked me to throw a placeholder ocean into the game. This shader looks fantastic it looks like you put a ton of thought into it.

**Comment by ufna** [comment]
Thank you! I hope it will be useful for you ;)

**Comment by daniel-dressler** [comment]
Yup double thanks from me! I put it in game and it works better than I hoped it to.
